### ISSUE TITLE
incorrect conversion: 將 normally should appear as "jiāng", but it appears as "qiāng".

### ISSUE THREAD

**Issue by luc-languagetools** [Language-Tools/python-pinyin-jyutping-sentence#4]
將 normally should appear as "jiāng", but it appears as "qiāng".

**Comment by lucwastiaux** [comment]
痠 appears as "痠", but it should be "suān"

**Comment by lucwastiaux** [comment]
痠 is fixed.

**Comment by chewmen** [comment]
Can we also please fix 吗 coming out as ma3?
And 呢 coming out as ni2?

**Comment by lucwastiaux** [comment]
@chewmen can you provide example sentences for 吗 and 呢 ?

**Comment by luc-languagetools** [comment]
fixed:
        '吗': 'ma',
        '呢': 'ne'
