### ISSUE TITLE
好 hao has 2 tones, but the addon can only recognize nihao

### ISSUE THREAD

**Issue by luc-languagetools** [Language-Tools/python-pinyin-jyutping-sentence#5]
FIXED '好': 'hao3',

**Comment by lucwastiaux** [comment]
* Chinese characters                               电子乐  （Electronic music ）
 * Pinyin that you got from the addon       diànzǐ lè
 * Pinyin that you expected                       diànzǐ yuè

**Comment by lucwastiaux** [comment]
* Chinese characters                                      胡同     （alley）
 * Pinyin that you got from the addon              hútóng
 * Pinyin that you expected                              hútòng

**Comment by lucwastiaux** [comment]
* Chinese characters                                     宝贝儿
 * Pinyin that you got from the addon             bǎobèiér
 * Pinyin that you expected                             bǎobèi er

**Comment by lucwastiaux** [comment]
* Chinese characters  在哪儿呢？                       
 * Pinyin that you got from the addon zai nǎr ní ？
 * Pinyin that you expected zài nǎr ne?

**Comment by lucwastiaux** [comment]
* Chinese characters  瓶盖 Bottle cap
 * Pinyin that you got from the addon pínggě
 * Pinyin that you expected píng gài

**Comment by lucwastiaux** [comment]
胡同, 宝贝儿, 瓶盖 fixed
